site_name: ODE's methods

theme:
  name: "material"

plugins: 
  - mkdocstrings

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
  - pymdownx.arithmatex

nav: 
  - Inicio: index.md
  - Código: reference.md
